FinalExam/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', lambda request:redirect('/blog/')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'blog.views.index', name='index'),

    url(r'^category/(?P<pk>\d+)/$', 'blog.views.category_detail', name='category_detail'),
    url(r'^category/new/$', 'blog.views.category_new', name='category_new'),
    url(r'^category/(?P<pk>\d+)/edit/$', 'blog.views.category_edit', name='category_edit'),

    url(r'^shop/(?P<pk>\d+)/$', 'blog.views.shop_detail', name='shop_detail'),
    url(r'^shop/new/$', 'blog.views.shop_new', name='shop_new'),
    url(r'^shop/(?P<pk>\d+)/edit/$', 'blog.views.shop_edit', name='shop_edit'),

    url(r'^shop/(?P<shop_pk>\d+)/review/new/$', 'blog.views.review_new', name='review_new'),
    url(r'^shop/(?P<shop_pk>\d+)/review/(?P<pk>\d+)/edit/$', 'blog.views.review_edit', name='review_edit'),
]

blog/models.py
from django.db import models

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

class Category(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:category_detail', args=[self.pk])

class Shop(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    about = models.TextField()
    photo1 = models.ImageField()
    photo2 = models.ImageField(blank=True)
    photo3 = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:shop_detail', args=[self.pk])

class Review(models.Model):
    shop = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Category, Shop, Review

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['message', 'photo']

accounts/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form' : form,
        })

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Shop, Review
from .forms import CategoryForm, ShopForm, ReviewForm

def index(request):
    category_list = Category.objects.all()
    review_list = Review.objects.all().order_by('-created_at')
    return render(request, 'blog/index.html', {
        'category_list' : category_list,
        'review_list' : review_list,
        })

def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'blog/category_detail.html', {
        'category' : category,
        })

def shop_detail(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    return render(request, 'blog/shop_detail.html', {
        'shop' : shop,
        })

@login_required
def category_new(request):
    if request.method =="POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save()
            messages.success(request, '새로운 카테고리가 등록되었습니다.')
            return redirect(category)
    else:
        form = CategoryForm()
    return render(request, 'blog/category_form.html', {
        'form': form,
        })

@login_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)

    if request.method =="POST":
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            messages.success(request, '카테고리 정보가 수정되었습니다.')
            return redirect(category)
    else:
        form = CategoryForm(instance=category)
    return render(request, 'blog/category_form.html', {
        'form': form,
        })

@login_required
def shop_new(request):
    if request.method =="POST":
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save()
            messages.success(request, '새로운 가게가 등록되었습니다.')
            return redirect(shop)
    else:
        form = ShopForm()
    return render(request, 'blog/shop_form.html', {
        'form': form,
        })

@login_required
def shop_edit(request, pk):
    shop = get_object_or_404(Shop, pk=pk)

    if request.method =="POST":
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.save()
            messages.success(request, '가게 정보가 수정되었습니다.')
            return redirect(shop)
    else:
        form = ShopForm(instance=shop)
    return render(request, 'blog/shop_form.html', {
        'form': form,
        })

@login_required
def review_new(request, shop_pk):
    shop = get_object_or_404(Shop, pk=shop_pk)

    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = shop
            review.user = request.user
            review.save()
            messages.success(request, '새로운 리뷰가 등록되었습니다.')
            return redirect(shop)
    else:
        form = ReviewForm()
    return render(request, 'blog/review_form.html', {
        'form' : form,
        })

@login_required
def review_edit(request, shop_pk, pk):
    review = get_object_or_404(Review, pk=pk)

    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = get_object_or_404(Shop, pk=shop_pk)
            review.user = request.user
            review.save()
            messages.success(request, '리뷰 내용이 수정되었습니다.')
            return redirect('blog:shop_detail', shop_pk)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'blog/review_form.html', {
        'form' : form,
        })

accounts/templates/accounts/signup_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="post" style="margin: 10% 10% 10% 10%;width:50%;">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" />
</form>
{% endblock %}

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Dante's Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
}

html {
  position: relative;
  min-height: 100%;
}

body {
  margin-bottom: 60px;
}

.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
</style>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Dante's Blog</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}?next={{request.path}}">로그아웃</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}?next={{request.path}}">로그인</a></li>
            <li><a href="{% url 'accounts:signup' %}?next={{request.path}}">회원가입</a></li>
          {% endif %}
        </ul>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

{% block content %}
{% endblock %}

<div class="footer">
    <div class="container">
        <p class="text-muted">벤처창업 웹프로그래밍 기말고사</p>
    </div>
</div>

</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h3>{{category.title}}
            <a href="{% url 'blog:category_edit' category.pk %}" class="btn btn-xs btn-default">
                수정
            </a>
        </h3>
            <ul>
            {% for shop in category.shop_set.all %}
                <a href="{% url 'blog:shop_detail' shop.pk %}" style="font-size: 18px;">
                    <li>{{ shop.title }}
                        <a href="{% url 'blog:shop_edit' shop.pk %}" class="btn btn-xs btn-default">
                            수정
                        </a>
                    </li>
                </a>
            {% endfor %}
            </ul>
            <br>
            <hr>
            <a href="{% url 'blog:shop_new' %}" class="btn btn-xs btn-primary btn-block">새로운 가게</a>
    </div>

</div>

{% endblock %}

blog/templates/blog/category_form.html
{% extends 'blog/base.html' %}

{% block content %}
{% load bootstrap3 %}
<form action="" method="post" enctype="multipart/form-data" style="margin: 5% 5%;width: 50%;">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button class="btn btn-primary">
            제출
        </button>
    {% endbuttons %}
</form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h2>카테고리</h2>
          {% for category in category_list %}
          <a href="{% url 'blog:category_detail' category.pk %}">
            <h3>{{category.title}}
              <a href="{% url 'blog:category_edit' category.pk %}" class="btn btn-sm btn-default">
                수정
              </a>
            </h3>

          </a>
          <ul>
            {% for shop in category.shop_set.all %}
              <a href="{% url 'blog:shop_detail' shop.pk %}" style="font-size: 18px;">
              <li>{{ shop.title }}
                <a href="{% url 'blog:shop_edit' shop.pk %}" class="btn btn-xs btn-default">
                수정
                </a>
              </li>
              </a>
            {% endfor %}
          </ul>
          {% endfor %}
          <br>
          <hr>
          <a href="{% url 'blog:category_new' %}" class="btn btn-xs btn-primary btn-block">새로운 카테고리</a>
          <a href="{% url 'blog:shop_new' %}" class="btn btn-xs btn-default btn-block">새로운 가게</a>
    </div>
    <div class="jumbotron">
    <h2>최근 등록된 리뷰</h2>
      <ul>
      {% for review in review_list|slice:":5" %}
        <a href="{% url 'blog:shop_detail' review.shop.pk %}" style="font-size: 18px;">
          <li>{{ review.message }} in {{ review.shop }} by {{ review.user }}</li>
        </a>
      {% endfor %}
</div>
{% endblock %}

blog/templates/blog/review_form.html
{% extends 'blog/base.html' %}

{% block content %}
{% load bootstrap3 %}
<form action="" method="post" enctype="multipart/form-data" style="margin: 5% 5%;width: 50%;">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button class="btn btn-primary">
            제출
        </button>
    {% endbuttons %}
</form>
{% endblock %}

blog/templates/blog/shop_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h3>{{shop.title}}
            <a href="{% url 'blog:shop_edit' shop.pk %}" class="btn btn-xs btn-default">
            수정
            </a>
        </h3>
        <img src="{{ shop.photo1.url }}">
        {% if shop.photo2 %}
        <img src="{{ shop.photo2.url }}">
        {% endif %}
        {% if shop.photo3 %}
        <img src="{{ shop.photo3.url }}">
        {% endif %}
        <h4>전화 번호 : {{shop.number}}</h4>
        <h4>주 소 : {{shop.address}}</h4>
        <h4>가게 설명 : {{shop.about}}</h4>
    </div>
    <div class="jumbotron">
    <h3>리뷰
    <a href="{% url 'blog:review_new' shop.pk %}" class="btn btn-xs btn-default">작성</a>
    </h3>
    {% for review in shop.review_set.all %}
        <div style="background-color: white;padding: 2px 1% 2px 1%;">
            <h5>{{review.message}}</h5>
            {% if review.photo %}
            <img src="{{ review.photo.url }}">
            {% endif %}
            <h6 style="color:gray;">by {{review.user}} | {{review.created_at}}
                <a href="{% url 'blog:review_edit' shop.pk review.pk %}">
                    수정
                </a>
            </h6>
        </div>
    {% endfor %}
    <br>
    <hr>

    <a href="{% url 'blog:index' %}" class="btn btn-default">가게 목록</a>
    </div>

</div>


{% endblock %}

blog/templates/blog/shop_form.html
{% extends 'blog/base.html' %}

{% block content %}

{% load bootstrap3 %}
<form action="" method="post" enctype="multipart/form-data" style="margin: 5% 5%;width: 50%;">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button class="btn btn-primary">
            제출
        </button>
    {% endbuttons %}

</form>

{% endblock %}